# This is a mock version of the keys implementation in MicroKeys
# It's only here so editors like VS Code will have autocomplete

"""Keyboard manipulation

This module mostly provides keyboard interactions:

* `key` - A function decoration used to register hot keys
* `KEY_xxx` - Various key definitions, such as `KEY_ALT`, `KEY_A`, and so on
* `press` - Press keys based off a string
* `press_raw` - Press keys based off a string, without looking for key codes
* `log` - Just log some output to the MicroKeys console

"""

from typing import Union, Callable

# Start of generated section -- Do not edit!
# This section is generated by create_key_constants.py, do not edit by hand
KEY_BREAK = 0x03
"""The break key."""
KEY_BACK = 0x08
"""The backspace key."""
KEY_BS = 0x08
"""The backspace key."""
KEY_BACKSPACE = 0x08
"""The backspace key."""
KEY_BKSP = 0x08
"""The backspace key."""
KEY_TAB = 0x09
"""The tab key."""
KEY_CLEAR = 0x0C
"""The 'clear' key, or numpad '5'."""
KEY_ENTER = 0x0D
"""The enter/return key."""
KEY_RETURN = 0x0D
"""The enter/return key."""
KEY_CAPSLOCK = 0x14
"""The caps lock key."""
KEY_CAPS = 0x14
"""The caps lock key."""
KEY_CAPS_LOCK = 0x14
"""The caps lock key."""
KEY_ESC = 0x1B
"""The escape key."""
KEY_ESCAPE = 0x1B
"""The escape key."""
KEY_SPACE = 0x20
"""The space bar."""
KEY_PAGEUP = 0x21
"""The page up key."""
KEY_PAGE_UP = 0x21
"""The page up key."""
KEY_PGUP = 0x21
"""The page up key."""
KEY_PAGEDOWN = 0x22
"""The page down key."""
KEY_PAGE_DOWN = 0x22
"""The page down key."""
KEY_PGDN = 0x22
"""The page down key."""
KEY_END = 0x23
"""The end key."""
KEY_HOME = 0x24
"""The home key."""
KEY_LEFT = 0x25
"""The left arrow key."""
KEY_UP = 0x26
"""The up arrow key."""
KEY_RIGHT = 0x27
"""The right arrow key."""
KEY_DOWN = 0x28
"""The down arrow key."""
KEY_PRINTSCREEN = 0x2C
"""The print screen key."""
KEY_PRINT_SCREEN = 0x2C
"""The print screen key."""
KEY_PRTSC = 0x2C
"""The print screen key."""
KEY_INS = 0x2D
"""The insert key."""
KEY_INSERT = 0x2D
"""The insert key."""
KEY_DEL = 0x2E
"""The delete key."""
KEY_DELETE = 0x2E
"""The delete key."""
KEY_HELP = 0x2F
"""The help key (not F1)."""
KEY_NUMLOCK = 0x90
"""The num lock key."""
KEY_NUM_LOCK = 0x90
"""The num lock key."""
KEY_NUM = 0x90
"""The num lock key."""
KEY_SCROLLLOCK = 0x91
"""The scroll lock key."""
KEY_SCROLL_LOCK = 0x91
"""The scroll lock key."""
KEY_SCROLL = 0x91
"""The scroll lock key."""
KEY_SEMI_COLON = 0xBA
"""The ';' key."""
KEY_SEMI = 0xBA
"""The ';' key."""
KEY_SEMICOLON = 0xBA
"""The ';' key."""
KEY_PLUS = 0xBB
"""The '+' key."""
KEY_COMMA = 0xBC
"""The ',' key."""
KEY_MINUS = 0xBD
"""The '-' key."""
KEY_DASH = 0xBD
"""The '-' key."""
KEY_PERIOD = 0xBE
"""The '.' key."""
KEY_DOT = 0xBE
"""The '.' key."""
KEY_SLASH = 0xBF
"""The '/' key."""
KEY_FORWARD_SLASH = 0xBF
"""The '/' key."""
KEY_FORWARDSLASH = 0xBF
"""The '/' key."""
KEY_BACK_QUOTE = 0xC0
"""The '`' key."""
KEY_BACKQUOTE = 0xC0
"""The '`' key."""
KEY_OPEN_BRACKET = 0xDB
"""The '[' key."""
KEY_OPENBRACKET = 0xDB
"""The '[' key."""
KEY_BACK_SLASH = 0xDC
"""The '' key."""
KEY_BACKSLASH = 0xDC
"""The '' key."""
KEY_CLOSE_BRACKET = 0xDD
"""The ']' key."""
KEY_CLOSEBRACKET = 0xDD
"""The ']' key."""
KEY_QUOTE = 0xDE
"""The ''' key."""
KEY_SINGLE_QUOTE = 0xDE
"""The ''' key."""
KEY_SINGLEQUOTE = 0xDE
"""The ''' key."""
KEY_ALT = 0x100
"""The alt modifier key."""
KEY_CONTROL = 0x200
"""The control modifier key."""
KEY_CTRL = 0x200
"""The control modifier key."""
KEY_SHIFT = 0x400
"""The shift modifier key."""
KEY_WIN = 0x800
"""The Windows modifier key."""
KEY_WINDOWS = 0x800
"""The Windows modifier key."""
KEY_0 = 0x30
"""The '0' key."""
KEY_1 = 0x31
"""The '1' key."""
KEY_2 = 0x32
"""The '2' key."""
KEY_3 = 0x33
"""The '3' key."""
KEY_4 = 0x34
"""The '4' key."""
KEY_5 = 0x35
"""The '5' key."""
KEY_6 = 0x36
"""The '6' key."""
KEY_7 = 0x37
"""The '7' key."""
KEY_8 = 0x38
"""The '8' key."""
KEY_9 = 0x39
"""The '9' key."""
KEY_A = 0x41
"""The 'A' key."""
KEY_B = 0x42
"""The 'B' key."""
KEY_C = 0x43
"""The 'C' key."""
KEY_D = 0x44
"""The 'D' key."""
KEY_E = 0x45
"""The 'E' key."""
KEY_F = 0x46
"""The 'F' key."""
KEY_G = 0x47
"""The 'G' key."""
KEY_H = 0x48
"""The 'H' key."""
KEY_I = 0x49
"""The 'I' key."""
KEY_J = 0x4A
"""The 'J' key."""
KEY_K = 0x4B
"""The 'K' key."""
KEY_L = 0x4C
"""The 'L' key."""
KEY_M = 0x4D
"""The 'M' key."""
KEY_N = 0x4E
"""The 'N' key."""
KEY_O = 0x4F
"""The 'O' key."""
KEY_P = 0x50
"""The 'P' key."""
KEY_Q = 0x51
"""The 'Q' key."""
KEY_R = 0x52
"""The 'R' key."""
KEY_S = 0x53
"""The 'S' key."""
KEY_T = 0x54
"""The 'T' key."""
KEY_U = 0x55
"""The 'U' key."""
KEY_V = 0x56
"""The 'V' key."""
KEY_W = 0x57
"""The 'W' key."""
KEY_X = 0x58
"""The 'X' key."""
KEY_Y = 0x59
"""The 'Y' key."""
KEY_Z = 0x5A
"""The 'Z' key."""
KEY_F1 = 0x70
"""The F1 function key."""
KEY_F2 = 0x71
"""The F2 function key."""
KEY_F3 = 0x72
"""The F3 function key."""
KEY_F4 = 0x73
"""The F4 function key."""
KEY_F5 = 0x74
"""The F5 function key."""
KEY_F6 = 0x75
"""The F6 function key."""
KEY_F7 = 0x76
"""The F7 function key."""
KEY_F8 = 0x77
"""The F8 function key."""
KEY_F9 = 0x78
"""The F9 function key."""
KEY_F10 = 0x79
"""The F10 function key."""
KEY_F11 = 0x7A
"""The F11 function key."""
KEY_F12 = 0x7B
"""The F12 function key."""
KEY_F13 = 0x7C
"""The F13 function key."""
KEY_F14 = 0x7D
"""The F14 function key."""
KEY_F15 = 0x7E
"""The F15 function key."""
KEY_F16 = 0x7F
"""The F16 function key."""
# End of generated section -- Do not edit!

def press(keys: str) -> None:
    """Performs a series of key presses

    `keys` can specify any single key or any key combined with Alt, Control, Shift, or any 
    combination.  Each key is represented by one or more characters, such as a for the 
    character "a", or {ENTER} for the Enter key.

    To combine a key with Shift, precede the key code with `+`. To combine a key with 
    Control, precede the key code with `^`. To combine a key with Alt, precede the key 
    code with `%`.
    """

    print(f"key.press('{keys}')")

def log(msg: str) -> None:
    """Logs a message to the display of MicroKeys

    No other action is taken, this is only to log message to help with debugging 
    and/or running macros.
    """

    print(f"key.log('{msg}')")

def press_raw(keys: str) -> None:
    """Performs a series of key presses

    `keys` is a string to be pressed out.  Only `\n`, '\t`, and '\b` are interpreted as 
    keys (Enter, Tab, and Backspace), the rest are typed as as is.
    """

    print(f"key.press('{keys}')")

def key(key_code: Union[int, str]) -> Callable:
    """Decoration for a function to register it as a macro key

    `key_code` is either a combination of KEY_xxx codes, or a string.  For key 
    codes, use one or more key codes, like `keys.KEY_ALT | keys.KEY_Z` will 
    register Alt+Z.  For strings, any string is allowed, and will not register 
    a key, the macro will only be calling by specifying the string on a call 
    to `MacroKeys.exe`.
    """
    def key_internal(func):
        return func
    return key_internal
